### ISSUE TITLE
Weird  error on windows

### ISSUE THREAD

**Issue by mic0331** [jwijffels/BelgiumMaps.Admin#1]
Hi there,

when I try to install the package 

`install.packages("BelgiumMaps.Admin", repos = "http://www.datatailor.be/rcube", type = "source")`

or 

`devtools::install_github("jwijffels/BelgiumMaps.Admin", build_vignettes = TRUE)`

I am getting an error message.

> Downloading GitHub repo jwijffels/BelgiumMaps.Admin@master
> from URL https://api.github.com/repos/jwijffels/BelgiumMaps.Admin/zipball/master
> Installing BelgiumMaps.Admin
> "C:/Program Files/R/R-3.4.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
>   "C:/Users/nenb317/AppData/Local/Temp/Rtmp2dIUhi/devtoolsef86607ef4/weRbelgium-BelgiumMaps.Admin-b5c639b" --library="C:/Program  \
>   Files/R/R-3.4.0/library" --install-tests 
> 
> 'C:\Program' is not recognized as an internal or external command,
> operable program or batch file.
> Installation failed: Command failed (1)

I suspect your package is not supported on Windows.  I will try later on a Unix based os.
If you can provide me a hint on where the problem might be I should be able to provide a pull request support.

Cheers

**Comment by jwijffels** [comment]
I'm on Windows and this works perfectly for me:

> install.packages("BelgiumMaps.Admin", repos = "http://www.datatailor.be/rcube", type = "source")
Installing package into ‘C:/Users/Jan/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'http://www.datatailor.be/rcube/src/contrib/BelgiumMaps.Admin_1.1.tar.gz'
Content type 'application/x-gzip' length 8767321 bytes (8.4 MB)
downloaded 8.4 MB

* installing *source* package 'BelgiumMaps.Admin' ...
** R
** data
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (BelgiumMaps.Admin)

**Comment by mic0331** [comment]
Strange ... on Rstudio or RGui I have similar issue 

```
> install.packages("BelgiumMaps.Admin", repos = "http://www.datatailor.be/rcube", type = "source")
essai de l'URL 'http://www.datatailor.be/rcube/src/contrib/BelgiumMaps.Admin_1.1.tar.gz'
Content type 'application/x-gzip' length 8767321 bytes (8.4 MB)
downloaded 8.4 MB

'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

Les packages source téléchargés sont dans
        ‘C:\Users\nenb317\AppData\Local\Temp\RtmpU3MnTE\downloaded_packages’
Warning messages:
1: l'exécution de la commande '"C:/Program Files/R/R-3.4.0/bin/x64/R" CMD INSTALL -l "C:\Program Files\R\R-3.4.0\library" C:\Users\nenb317\AppData\Local\Temp\RtmpU3MnTE/downloaded_packages/BelgiumMaps.Admin_1.1.tar.gz' renvoie un statut 1 
2: In install.packages("BelgiumMaps.Admin", repos = "http://www.datatailor.be/rcube",  :
  l'installation du package ‘BelgiumMaps.Admin’ a eu un statut de sortie non nul
> 

```
It complains about "C\Program" - I guess it try to find R, in my case it is installed in `C:\Program Files\R\R-3.4.0`

Thanks anyway for your quick reply,

**Comment by jwijffels** [comment]
The issue is not related to the package. See here. https://stackoverflow.com/questions/10077689/r-cmd-on-windows-7-error-r-is-not-recognized-as-an-internal-or-external-comm
Maybe you need to install Rtools https://cran.r-project.org/bin/windows/Rtools/

**Comment by mic0331** [comment]
:+1:

On my computer, R was installed in a non-standard location (`c:\Program files ...`).  I re-install R in the `C:\` so I don't have any space in my path to R.

This fixed the problem.  

Thanks for your support, I will, now, explore your work 

BR
Michaël

Note, worth nothing, installing this package `BelgiumMaps.Admin` directly from CRAN requires several packages to be installed like `stringi` - directly from GitHub with devtools install all the dependencies.

**Comment by jwijffels** [comment]
Good that this solved your issue.
Mark that this is a newer package with admin boundaries of Belgium: https://github.com/bnosac/BelgiumMaps.StatBel and is based on official data. While this package in this repository was based on data from OpenStreetmap
